function norm_pos = get_normalized_pos(pos)
    norm_pos = [pos(1)/1024, pos(2)/768, pos(3)/1024, pos(4)/768];
endfunction

function h = ui_create_panel(parent, position, bg_color)
    norm_pos = get_normalized_pos(position);
    h = uicontrol(parent, ...
        "style", "frame", ...
        "units", "normalized", ...
        "position", norm_pos, ...
        "backgroundcolor", bg_color, ...
        "relief", "flat");
endfunction

function h = ui_create_text(parent, position, string_val, font_size, fg_color, bg_color)
    norm_pos = get_normalized_pos(position);
    h = uicontrol(parent, ...
        "style", "text", ...
        "string", string_val, ...
        "units", "normalized", ...
        "position", norm_pos, ...
        "backgroundcolor", bg_color, ...
        "foregroundcolor", fg_color, ...
        "fontname", "Arial", ...
        "fontsize", font_size, ...
        "horizontalalignment", "center");
endfunction

function h = ui_create_button(parent, position, string_val, callback_str, theme)
    norm_pos = get_normalized_pos(position);
    h = uicontrol(parent, ...
        "style", "pushbutton", ...
        "string", string_val, ...
        "units", "normalized", ...
        "position", norm_pos, ...
        "backgroundcolor", theme.accent, ...
        "foregroundcolor", theme.bg_main, ... 
        "fontname", theme.font_body, ...
        "fontsize", theme.font_size_body, ...
        "fontweight", "bold", ...
        "relief", "flat", ...
        "callback", callback_str);
endfunction

function h = ui_create_slider(parent, position, min_val, max_val, start_val, callback_str, theme)
    norm_pos = get_normalized_pos(position);
    h = uicontrol(parent, ...
        "style", "slider", ...
        "units", "normalized", ...
        "position", norm_pos, ...
        "min", min_val, ...
        "max", max_val, ...
        "value", start_val, ...
        "backgroundcolor", theme.bg_panel, ...
        "callback", callback_str);
endfunction