// Creates a flat, modern panel (card) to hold other elements
function h = ui_create_panel(parent, position, bg_color)
    h = uicontrol(parent, ...
        "style", "frame", ...
        "position", position, ...
        "backgroundcolor", bg_color, ...
        "relief", "flat"); // Scilab uses 'relief' to handle borders
endfunction

// Creates clean text with standard alignments
function h = ui_create_text(parent, position, string_val, font_size, fg_color, bg_color)
    h = uicontrol(parent, ...
        "style", "text", ...
        "string", string_val, ...
        "position", position, ...
        "backgroundcolor", bg_color, ...
        "foregroundcolor", fg_color, ...
        "fontname", "Arial", ...
        "fontsize", font_size, ...
        "horizontalalignment", "center"); // Changed to center for better layout
endfunction

// Creates a prominent, clickable action button
function h = ui_create_button(parent, position, string_val, callback_str, theme)
    h = uicontrol(parent, ...
        "style", "pushbutton", ...
        "string", string_val, ...
        "position", position, ...
        "backgroundcolor", theme.accent, ...
        "foregroundcolor", theme.bg_main, ... 
        "fontname", theme.font_body, ...
        "fontsize", theme.font_size_body, ...
        "fontweight", "bold", ...
        "relief", "flat", ...
        "callback", callback_str);
endfunction